---
# File: site.yml - Example Vault site playbook

- name: Install Vault
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: brianshumate.vault}
